INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El sexto sentido', 'M. Night Shyamalan', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Pulp Fiction', 'Tarantino', 'Acción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Todo Sobre Mi Madre', 'Almodóvar', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('300', 'Zack Snyder', 'Acción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El silencio de los corderos', 'Jonathan Demme', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Forrest Gump', 'Robert Zemeckis', 'Comedia');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Las Hurdes', 'Luis Buñuel', 'Documental');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('La La Land', 'Damien Chazelle', 'Musical');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Gladiador', 'Ridley Scott', 'Acción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Padrino', 'Francis Ford Coppola', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Amélie', 'Jean-Pierre Jeunet', 'Comedia');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Interestelar', 'Christopher Nolan', 'Ciencia Ficción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('La Lista de Schindler', 'Steven Spielberg', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Club de la Pelea', 'David Fincher', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Inception', 'Christopher Nolan', 'Ciencia Ficción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('La Vida es Bella', 'Roberto Benigni', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Gran Hotel Budapest', 'Wes Anderson', 'Comedia');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Matrix', 'Hermanas Wachowski', 'Ciencia Ficción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Parásitos', 'Bong Joon-ho', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Toy Story', 'John Lasseter', 'Animación');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Rey León', 'Roger Allers, Rob Minkoff', 'Animación');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Titanic', 'James Cameron', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Mad Max: Furia en la carretera', 'George Miller', 'Acción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Avatar', 'James Cameron', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Laberinto del Fauno', 'Guillermo del Toro', 'Fantasía');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('Requiem por un Sueño', 'Darren Aronofsky', 'Drama');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('La Naranja Mecánica', 'Stanley Kubrick', 'Ciencia Ficción');
INSERT INTO pelicula (nombre, director, clasificacion) VALUES ('El Viaje de Chihiro', 'Hayao Miyazaki', 'Animación');
